# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.0

jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run:
        name: "Get Pandoc and install it"
        command: |
          wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
          dpkg -i pandoc-2.7.2-1-amd64.deb
    - run:
        name: "Make assessment.docx"
        command: make
    - persist_to_workspace:
        root: .
        paths:
        - assessment.docx

  publish_github_release:
    docker:
    - image: golang:1.8
    steps:
    - attach_workspace:
        at: .
    - run:
        name: "Publish Release on GitHub"
        command: |
          ls -l assessment.docx
          go get github.com/tcnksm/ghr
          VERSION=${CIRCLE_BRANCH}
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${VERSION} ./assessment.docx

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  build_publish:
    jobs:
      - build
      - publish_github_release:
          requires:
          - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
